#!/bin/bash

echo "🚀 Firebase Hosting Deployment Guide"
echo "======================================"
echo ""
echo "Follow these steps to deploy your app:"
echo ""
echo "1. Authenticate with Firebase:"
echo "   npx firebase login"
echo ""
echo "2. Initialize your project (if not done already):"
echo "   npx firebase use --add"
echo "   # Select your Firebase project from the list"
echo ""
echo "3. Deploy to Firebase Hosting:"
echo "   npx firebase deploy --only hosting"
echo ""
echo "Your app will be available at: https://your-project-id.web.app"
echo ""
echo "📁 Build files are ready in: ./dist/public"
echo "⚙️  Firebase config is ready in: ./firebase.json"
echo ""
echo "🎉 Everything is configured and ready to deploy!"
